### ISSUE TITLE
Content for Tonie-Figure is overwritten by download each time

### ISSUE THREAD

**Issue by jackydany** [toniebox-reverse-engineering/teddy#10]
Hi there and THANKS for the great work!
i love the teddy app and the new teddybench.
i also manged to mod the first toniebox to get access to the sd card without opening it. now i can test and play around like i did today.

i got a question and a problem.

question:
when i double click a tonie, i get the uid, i copy this.
then i drag'n'drop a mp3 on this tonie (lion) and the bench opens a new window with the uid field, i paste the copied uid from the lion.
teddy starts to encode and finishes fine. but then the lion picture is exchanged with a random teddy-pic and the name is gone and instead it says the uid and unknow.....
is this normal behavior?
i really would appreciate if the lion picture stays and i can rename it to remember what i put on the tonie.

problem:
as soon as i put the lion-tonie on the box with the edited sd card, the box starts to download the original soundfile and starts playing the lion-audiobook.
tried several audiofiles and many attemps, always same behaviour.
cant get it to work this way. there wqas 1 attemp that did work, but then i deleted the file from the card via toniebench to reassign a new audiofile, since that.... didnt work anymore.

help would be appreciated.

keep on with the work

ps:
i read about the right-click menue, this is not in the latest release right? only if i compile it myself, right?

THANKS A LOT!

**Comment by Gambrius** [comment]
Hallo Jackydany,

The picture shown in TeddyBench represents the original audio content identified by their audio ID and their checksum (Hash) value.

So as soon as you would connect the UID of your existing original Tonie figurine with own content the picture would change because your audio does not have the dame checksum as the original one. But you can rename the „unknown“ tag. That way you can keep an overview by your custom tonies.

Using an original Tonie to exchange the content is not that easy than using your own / new RFID tag. Thats because of how Boxine (company that owns the Tonie brand) is verifying wether there is new content within the Tonie Cloud for their content Tonies and their creative Tonies.
By verifying the UID and the audioID of the audio file connected to the UID on your SD card with the Tonie Cloud it will download the original content. Thats because to this specific UID there is just the audioID of the original audio content stored and linked to.
But if you set the audioID of your custom content to the same value as the original content your custom audio files will stay on the box because it will pass the verification of the given UID and audioID with the Tonie Cloud.
Unfortunately setting the audioID to a given value while encoding custom audio is right now just possible with the command line Tool Teddy.

I hope I was able to explain a bit of the background processes within the Tonie universe and that it is unedrstandable so far.

In addition I will add to the „needed feature“ list two points:
- adding their own art work into TeddyBench
- adding the feature of setting the audioID prior to encoding of new files.

Regards,
Gambrius

**Comment by jackydany** [comment]
Hi and thanks for the fast reply.
We already had some exchange on your blog :D Thanks for that also!

I thought with the bench it is possible to "just add" new content to an existing tonie. Ok so its still possible via the cli tool.
fair enough, no problem.

so it would be nice to have the "add" options for a regular tonie figurine on right button click.
maybe also replace and add, so you can add a file without having to reencode the whole files. dont know if that is possible at all. dont think so.

another enhacement as question:
would it be possible to set a value for chapters?
what i mean..... i have a large mp3 audiobook, set the value to 10 minutes and on encoding the teddy tool with "chop" the file into chapters of 10 minutes lenght each.

I will take some fotos and explanations on my sd card mod and contact you, maybe you can post them on your blog if you like. but thats just an idea, will write you an email then.

thake care and thanks a lot again and again :D

**Comment by jackydany** [comment]
ahhh and could you provide the pictures as a zip file for download so that the tool doesnt need to fetch them via json file from your webspace? would be good for your traffic and one could store the files local for offline use for example :D

**Comment by Gambrius** [comment]
Hallo,

Adding a track to an existing tonie audio file is only with a complete new encoding of all audio tracks possible.
We will think about possibilities in this case.

Regarding the chapters:
I understand that this kind of feature would be a great thing for the use case audio books. Out of my point of view we have to take care not to overload the TeddyBench Tool. It is not an audio editing tool. It is a tool to close the bridge between the closed system Toniebox and the demand to get the control back for custom content and custom tags.
To chop an audio file into several parts, there are already good tools on the market.
But we are always interested to enhanced the features of TeddyBench. Thats why we will think about these kind of features as well.

Pics:
The new revision we have in testing already includes a caching feature for using TeddyBench in offline mode. This includes saving the JSON file and the pics.

Looking forward to your eMail.

Regards,
Gambrius

**Comment by jackydany** [comment]
great thanks! copletly understand the point of view regarding the chopping.... for my usecase it just would be nice... still nothing to complain if not integrated ;)
greetings

**Comment by jackydany** [comment]
last question (i hope):
in what format do i have to put the audio id in the teddy clie tool?
if i want to encode the lion with my own content, i use: teddy -m info d:\content\directoy\file
i get and AudioID in format 0x666DDD66D (whatever)
if i put this audioID into the new content using: teddy -m encode directorytoMP3 --id=0x666DDD66D the lio downloads the original content as soon as i put the tonie figurine on the box.
i also tried the audioID from the bench, thats not HEX but numeric.... also didnt work.

thanks

**Comment by Gambrius** [comment]
You have to use the four byte hex value but without the 0x.

**Comment by jackydany** [comment]
Error: You must specify the AudioID as hex value like 0x66DD66DD or as decimal number like 1234567890

so i need the 0x but why doesnt it work then?

**Comment by jackydany** [comment]
THanks for the help!
