### ISSUE TITLE
Password Settings

### ISSUE THREAD

**Issue by nfc232** [toniebox-reverse-engineering/teddy#19]
I want to read the content of the original tonie, but the password is wrong. It works only with the custom tags. How can i change it in the application?

**Comment by Gambrius** [comment]
How can you tell that TeddyBench is using a wrong password?
If you hook up a proxmark3 with the correct firmware installed, it should be able to read the original tonies as well.

**Comment by nfc232** [comment]
Only the custom tag works with 0F0F0F0F
[PM3] UnlockTag: Send request for pass 0x0F0F0F0F
[PM3] UnlockTag:   String ' [x] Set password'
[PM3] UnlockTag:   String ' [x] Success'

The other tries dont work
[PM3] UnlockTag: Send request for pass 0xDEADBEEF
[PM3] UnlockTag:   String ' [x] Set password'
[PM3] UnlockTag:   String '   [i] No tag found'

[PM3] UnlockTag: Send request for pass 0x7FFD6E5B
[PM3] UnlockTag:   String ' [x] Set password'
[PM3] UnlockTag:   String '   [i] No tag found'

Request with the original tonie
[PM3] MeasureAntenna: Start
[PM3] GetResponse: Send 02B2048E3C
[PM3] GetResponse: no tag answered, returning
[PM3] GetRandom: Failed (no resp)

**Comment by Gambrius** [comment]
It is because the RFID tag within the original Tonie has just a small antenna, wich needs to sit within the sweet spot. In combination with the proxmark3 easy it is in some cases hard to hit the sweet spot. Try another original tonie. Try to put the tonie in another orientation or position onto the proxmark.

All the correct passwords are included.
